name: Build and Publish Python Package

on:
  push:
    branches:
      - main

# Build and publish package 
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Set up Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install build dependencies
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      # 4. Build the package
      - name: Build release distributions
        run: python -m build
      
      - name: Debug secret
        run: echo "Token length ${#TWINE_PASSWORD}" 
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      # 5. Publish to PyPI
      - name: Publish release distributions to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} 
        run: python -m twine --verbose upload dist/*
